#!/usr/bin/env bash

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARAM_OVERWRITES:LIST=-DPARAM_NUM_CELLS=256;-DPARAM_PRECISION=precision64Bit"
flags[1]="-DPARAM_OVERWRITES:LIST=-DPARAM_NUM_CELLS=256;-DPARAM_PRECISION=precision32Bit"


################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
