#!/usr/bin/env bash
#
# Copyright 2015-2016 Alexander Grund
#
# This file is part of ParaTAXIS.
#
# ParaTAXIS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ParaTAXIS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ParaTAXIS.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=1;-DPARAM_GENERATOR=DoubleSlit;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[1]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=DoubleSlit;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[2]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=DoubleSlit;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=0"
flags[3]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=1;-DPARAM_GENERATOR=Edge;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[4]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=Edge;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[5]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=Edge;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=0"
#Single
flags[6]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=DoubleSlit;-DPARAM_PRECISION=precision32Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[7]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=DoubleSlit;-DPARAM_PRECISION=precision32Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=0"
flags[8]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=1;-DPARAM_GENERATOR=Edge;-DPARAM_PRECISION=precision32Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[9]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=Edge;-DPARAM_PRECISION=precision32Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[10]="-DPARAM_OVERWRITES:LIST=-DPARAM_ROOM_WIDTH=999999;-DPARAM_GENERATOR=Edge;-DPARAM_PRECISION=precision32Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=0"
# Grid
flags[11]="-DPARAM_OVERWRITES:LIST=-DPARAM_INITIAL_DENSITY=0.01;-DPARAM_ROOM_WIDTH=512;-DPARAM_GENERATOR=CombinedGenerator;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=1"
flags[12]="-DPARAM_OVERWRITES:LIST=-DPARAM_INITIAL_DENSITY=0.01;-DPARAM_ROOM_WIDTH=512;-DPARAM_GENERATOR=CombinedGenerator;-DPARAM_PRECISION=precision64Bit -DPARATAXIS_FORCE_SINGLE_SCATTERING=0"

################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
