#!/usr/bin/env bash

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_OFFSET_X=666"
flags[1]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_OFFSET_X=666"
flags[2]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=CountParticles"
flags[3]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=CountParticles"
flags[4]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles"
flags[5]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles"
flags[6]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles;-DPARAM_GENERATOR=RaisingLine;-DPARAM_SCATTERER=LinearDensity;-DPARAM_FACTORZ=0.00007 -DCUDA_FAST_MATH=OFF"
flags[7]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles;-DPARAM_GENERATOR=RaisingLine;-DPARAM_SCATTERER=LinearDensity;-DPARAM_FACTORZ=0.00007"


################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
