#!/usr/bin/env bash
#
# Copyright 2015-2016 Alexander Grund
#
# This file is part of ParaTAXIS.
#
# ParaTAXIS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ParaTAXIS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ParaTAXIS.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_OFFSET_X=666"
flags[1]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_OFFSET_X=666"
flags[2]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=CountParticles"
flags[3]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=CountParticles"
flags[4]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles"
flags[5]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles"
flags[6]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles;-DPARAM_GENERATOR=RaisingLine;-DPARAM_SCATTERER=LinearDensity;-DPARAM_FACTORZ=0.00007 -DCUDA_FAST_MATH=OFF"
flags[7]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles;-DPARAM_GENERATOR=RaisingLine;-DPARAM_SCATTERER=LinearDensity;-DPARAM_FACTORZ=0.00007"
flags[8]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_SCATTERER=DoubleRandDirection;-DPARAM_LASER_STEP_LEN=100000;-DPARAM_LASER_DISTRIBUTION=PtOnly"
flags[9]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_SCATTERER=DoubleRandDirection;-DPARAM_LASER_STEP_LEN=100000;-DPARAM_LASER_DISTRIBUTION=PtOnly"
flags[10]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_SCATTERER=RandomDirection;-DPARAM_LASER_STEP_LEN=100000;-DPARAM_LASER_DISTRIBUTION=PtOnly"
flags[11]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_SCATTERER=RandomDirection;-DPARAM_LASER_STEP_LEN=100000;-DPARAM_LASER_DISTRIBUTION=PtOnly"
flags[12]="-DXRT_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLEHANDLER=AddWaveParticles;-DPARAM_GENERATOR=DoublePoint"


################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
