#!/usr/bin/env bash
#
# Copyright 2015-2016 Alexander Grund
#
# This file is part of ParaTAXIS.
#
# ParaTAXIS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ParaTAXIS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ParaTAXIS.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARATAXIS_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PARTICLEHANDLER=AddWaveParticles;-DPARAM_FIELD_MANIPULATOR=Random;-DPARAM_LASER_PHOTON_CT=Const"
flags[1]="-DPARATAXIS_VERBOSE=13 -DPARAM_OVERWRITES:LIST=-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_FIELD_MANIPULATOR=Random;-DPARAM_LASER_PHOTON_CT=Const"
flags[2]="-DPARATAXIS_VERBOSE=255 -DPARAM_OVERWRITES:LIST=-DPARAM_PARTICLEHANDLER=CountParticles;-DPARAM_FIELD_MANIPULATOR=HDF5Interpolator;-DPARAM_LASER_PHOTON_CT=HDF5Profile"


################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
